export const defaults = {
  checkin_points: 2,
  short_comment_points: 2,
  long_comment_points: 5,
  article_points: 10,
  image_points: 10,
  video_points: 10,
  chat_points: 3,
  post_threshold: 10,
  comment_threshold: 30,
  comment_daily_cap: 6,
  chat_daily_limit: 2,
  locked_threshold: 30,
  locked_enabled: true,
  locked_categories: ['article', 'image'],
  min_public_chars: 50,
  min_public_images: 1,
  image_max_mb: 50,
  image_max_count: 20,
  video_max_mb: 500,
  video_max_count: 3,
  quiz_pass_score: 10,
  quiz_draw_count: 1,
  ban_login_mode: 'reason',
};
export const categories: any = {
  article: {
    name: '发文区',
    description: '把故事与心动写下来',
    color: 'purple',
  },
  image: { name: '发图区', description: '收集每一帧喜欢', color: 'pink' },
  video: { name: '视频区', description: '热爱，在此刻播放', color: 'blue' },
  chat: { name: '水区', description: '今天也想和你聊聊', color: 'yellow' },
};
export function effective(s: string) {
  return [...s.normalize('NFKC').replace(/[\s\p{Cf}\p{Cc}]/gu, '')].length;
}
export function normalize(s: string) {
  return s.normalize('NFKC').replace(/[\s\p{Cf}\p{Cc}]/gu, '');
}
export const messages: any = {
  INCOMPLETE_QUIZ: '请完成全部必答题。',
  FAIL: '未通过论坛准入验证',
  QUIZ_NOT_PASSED: '请先完成准入答题，验证有效期为30分钟。',
  USERNAME_EXISTS: '这个用户名已经有人使用了。',
  EMAIL_EXISTS: '这个邮箱已经注册，请直接登录。',
  INVALID_USERNAME: '用户名须为3–20位英文字母或数字。',
  INVALID_EMAIL: '请输入有效的邮箱地址。',
  PASSWORD_TOO_SHORT: '密码至少需要8位。',
  WEAK_PASSWORD: '密码必须同时包含英文字母和数字。',
  PASSWORD_NOT_MATCH: '两次输入的密码不一致。',
  USER_NOT_FOUND: '未找到这个账号。',
  WRONG_PASSWORD: '密码不正确，请重试。',
  ACCOUNT_BANNED: '账号当前处于封禁状态。',
  UNAUTHORIZED: '请先登录账号。',
  FORBIDDEN: '你没有进行此操作的权限。',
  EMPTY_TITLE: '请填写帖子标题。',
  EMPTY_CONTENT: '请填写正文。',
  EMPTY_COMMENT: '请填写评论，空格不计入有效内容。',
  IMAGE_REQUIRED: '发图区至少需要上传1张图片。',
  VIDEO_REQUIRED: '视频区至少需要一个上传完成的视频。',
  PUBLIC_CONTENT_TOO_SHORT: '请保留足够的公开正文。',
  PUBLIC_IMAGE_REQUIRED: '请至少保留一张公开图片。',
  POST_PERMISSION_DENIED: '积分不足，暂未解锁发帖功能。',
  COMMENT_PERMISSION_DENIED: '积分不足，暂未解锁评论功能。',
  LOCKED_CONTENT_PERMISSION_DENIED: '该部分内容尚未解锁。',
  INVALID_IMAGE_TYPE: '图片仅支持 JPG、PNG、WEBP、GIF。',
  INVALID_VIDEO_TYPE: '视频仅支持 MP4、WEBM、MOV。',
  IMAGE_TOO_LARGE: '图片超过大小限制。',
  VIDEO_TOO_LARGE: '视频超过大小限制。',
  TOO_MANY_IMAGES: '图片数量超过限制。',
  TOO_MANY_VIDEOS: '视频数量超过限制。',
  UPLOAD_FAILED: '上传失败，请重新上传。',
  UPLOAD_INTERRUPTED: '上传尚未完成，请继续上传。',
  ALREADY_CHECKED_IN: '今天已经签到过了，明天再来吧。',
  NOT_FOUND: '内容不存在或已被移除。',
  RATE_LIMITED: '操作过于频繁，请稍后重试。',
  INVALID_SETTINGS: '请检查设置数值与题目配置。',
  SETUP_DISABLED: '管理员已初始化，或初始化凭证无效。',
  LOCKED_NOT_ALLOWED: '当前板块不允许新增待解锁内容。',
  CONFLICT: '内容已经更新，请刷新后再试。',
};
